version: '3.8'

services:
  # Base de dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: exam_postgres
    environment:
      POSTGRES_DB: exam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # API Flask
  api:
    build: ../api
    container_name: exam_api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/exam_db
      JWT_SECRET_KEY: your-secret-key-here
      FLASK_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy

  # Frontend Next.js
  frontend:
    build: .
    container_name: exam_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: 